version: '3.8'
services:

  postgres:
    image: postgres:15
    container_name: menudb-postgres
    environment:
      POSTGRES_DB: menudb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: menudb-mongo
    environment:
      MONGO_INITDB_DATABASE: menudb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data: