# Estrategia del motor
app.tree-strategy=custom

# Persistencia activa
app.storage=memory

# Evitar error de PostgreSQL y MongoDB al arrancar en modo memoria
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
#Definir puerto
server.port=8082