# Estrategia del motor
app.tree-strategy=custom

# Persistencia activa
app.storage=mongo
spring.profiles.active=mongo

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Puerto
server.port=8082